/**
 * Seals a private page so only its password can open it.
 *
 *   npm run vault:seal -- <name> [path]
 *
 * Reads the plaintext from `vault/<name>.json` (gitignored — it never leaves your machine),
 * asks for the password (or reads VAULT_PASSWORD), and writes the ciphertext to
 * `src/content/vault/sealed/<hash>.ts`. The page opens at `path` (default `/<name>`).
 *
 * Re-run it to change a password or the content; the old sealed file for that path is replaced.
 * Use a long passphrase: a static site can't rate-limit guesses against the ciphertext.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { createInterface } from 'node:readline'
import { fileURLToPath } from 'node:url'

import { sealVault } from '../src/lib/vault.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const [name, routePath] = process.argv.slice(2)

if (!name || !/^[a-z0-9-]+$/i.test(name)) {
  console.error('Usage: npm run vault:seal -- <name> [path]   (reads vault/<name>.json)')
  process.exit(1)
}

/** Prompts without echoing what is typed. */
function askHidden(question: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout, terminal: true })
    const output = rl as unknown as { _writeToOutput: (text: string) => void; output: NodeJS.WriteStream }
    let prompted = false
    output._writeToOutput = (text: string) => {
      if (!prompted) {
        output.output.write(text)
        prompted = true
      } else if (text.includes('\n')) output.output.write('\n')
      else output.output.write('*')
    }
    rl.question(question, (answer) => {
      rl.close()
      resolve(answer)
    })
  })
}

const source = join(root, 'vault', `${name}.json`)
const payload = JSON.parse(await readFile(source, 'utf8')) as unknown

let password = process.env.VAULT_PASSWORD ?? ''
if (!password) {
  password = await askHidden('Password: ')
  const confirm = await askHidden('Repeat:   ')
  if (password !== confirm) {
    console.error('Passwords did not match.')
    process.exit(1)
  }
}
if (!password) {
  console.error('A password is required.')
  process.exit(1)
}
if (password.length < 10) {
  console.warn('Heads up: short passwords can be guessed offline against the ciphertext. Sealing anyway.')
}

const vault = await sealVault(routePath ?? `/${name}`, payload, password)
const directory = join(root, 'src', 'content', 'vault', 'sealed')
// Named by the path's hash, so re-sealing the same path replaces its file.
const file = join(directory, `${vault.id.slice(0, 12)}.ts`)
await mkdir(directory, { recursive: true })

await writeFile(
  file,
  `import type { SealedVault } from '@/lib/vault'\n\n/** Generated by \`npm run vault:seal\`. Ciphertext only — do not edit. */\nexport const vault: SealedVault = ${JSON.stringify(vault, null, 2)}\n`,
)
console.log(`Sealed vault/${name}.json → ${file.slice(root.length + 1)}`)
