import type { SealedVault } from '@/lib/vault'

/** Generated by `npm run vault:seal`. Ciphertext only — do not edit. */
export const vault: SealedVault = {
  "v": 1,
  "id": "79ef960850423377d8468cb738ef3385b61aafe9a16a440359c9b8a554243ff8",
  "iterations": 600000,
  "salt": "mIF4lZwytKnzaX+tPUfhRw==",
  "iv": "ExrHDr+Ry7So67no",
  "data": "s0cASG+H1l7ypVq7gE7H560kpD7h7CETZhI/F7nns1QJTShmACKrRqa1nJmUaJGL607THCVt07YCYpzGySgJJ3diflP7TJFZJY9yTcVnWoCa839kDoX9cGG8N5dJ3hhBvDydPLqBo7iuQwzDKs3TNiKeeaHhA8vfeMoNkpIFGREF9e1kUTkBu3arVAS6iNO+nnojS3KLsR3kpPMMncH7AtgH/4FJCU0J3/iGyRvYcOdEELPoxYStSnlVtnvv6o5BuUrp2C6AFfmta/oKkB1xzSEibbSFOjtY3KoIzMWpLGwqHfx4ZFZrMLAdCJdTOu6ub3nEfwnrWvbLbdnYfDbMPUo4c6Cyyk0i9tHrwQ=="
}
